#if !canImport(ObjectiveC)
import XCTest

extension PrefixSuffixTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrefixSuffixTests = [
        ("testPrefix", testPrefix),
        ("testRemovingPartial", testRemovingPartial),
        ("testSuffix", testSuffix),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testEndsWith", testEndsWith),
        ("testSlicing", testSlicing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PrefixSuffixTests.__allTests__PrefixSuffixTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
